### ISSUE TITLE
Issues found while testing network with GoCart Concert setup

### ISSUE THREAD

**Issue by asmodehn** [robotics-in-concert/rocon_multimaster#314] opened 2015-07-13 07:55 UTC
- [ ] Exception when losing network ( disconnected from the wifi network using KDE network UI ): 

```
[WARN] [WallTime: 1436773680.891593] Gateway Hub : pinger update [Error connecting to 192.168.3.10:6380. timed out.]
[INFO] [WallTime: 1436773680.892668] Gateway : lost connection with hub, attempting to disconnect...
[INFO] [WallTime: 1436773691.113990] Gateway : disengaged connection with the hub [GoCart Concert][192.168.3.10:6380]
[INFO] [WallTime: 1436773691.624060] Gateway : discovered hub directly [http://192.168.3.10:6380]
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/opt/groot/rocon_ws/install/lib/python2.7/dist-packages/rocon_hub_client/hub_discovery.py", line 119, in run
    result, _ = self.discovery_update_hook(hostname, port)
  File "/opt/groot/rocon_ws/install/lib/python2.7/dist-packages/rocon_gateway/gateway_node.py", line 152, in _register_gateway
    existing_advertisements
  File "/opt/groot/rocon_ws/install/lib/python2.7/dist-packages/rocon_gateway/hub_manager.py", line 220, in connect_to_hub
    gateway_ip,
  File "/opt/groot/rocon_ws/install/lib/python2.7/dist-packages/rocon_gateway/gateway_hub.py", line 131, in register_gateway
    old_key = self._redis_server.get(self._redis_keys['public_key'])
  File "/opt/groot/rocon_ws/install/lib/python2.7/dist-packages/rocon_python_redis/client.py", line 528, in get
    return self.execute_command('GET', name)
  File "/opt/groot/rocon_ws/install/lib/python2.7/dist-packages/rocon_python_redis/client.py", line 349, in execute_command
    connection.send_command(*args)
  File "/opt/groot/rocon_ws/install/lib/python2.7/dist-packages/rocon_python_redis/connection.py", line 300, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/opt/groot/rocon_ws/install/lib/python2.7/dist-packages/rocon_python_redis/connection.py", line 282, in send_packed_command
    self.connect()
  File "/opt/groot/rocon_ws/install/lib/python2.7/dist-packages/rocon_python_redis/connection.py", line 229, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 101 connecting 192.168.3.10:6380. Network is unreachable.
```
- [ ] #317 Conductor confused if pull rules already exists -> this applies to both 'missing' and 'gone' robot states.
- [ ] #318 robot gateway not cleaning it s flipped topics on shutdown -> this is a nice to have, but should not be relied on to guaranteed the system is always working.

**Comment by jihoonl** [comment] 2015-07-13 09:35
#310 also fails in [register_gateway](https://github.com/robotics-in-concert/rocon_multimaster/blob/develop/rocon_gateway/src/rocon_gateway/gateway_hub.py#L98-L147).

Would be similar issue.

**Comment by stonier** [comment] 2015-07-14 01:09
Q) Happening every time? Or just sometimes?

**Comment by asmodehn** [comment] 2015-08-04 08:31
added 2 issues to the top comment.

**Comment by stonier** [comment] 2015-08-18 03:54
Closing this. Fixed some issues with the flipping (but not pulling). Conductor-gateway connectivity should use a more systematic approach to providing data and reproducing bugs, finding root causes and making plans to fix than the noise we currently have.

Let's close this and tackle the problem anew with the gopher conductor.

**Closed as completed** 2015-08-18 03:57 UTC
Labels: wontfix
