### ISSUE TITLE
Overlook large size topic

### ISSUE THREAD

**Issue by mmurooka** [robotics-in-concert/rocon_multimaster#293] opened 2014-12-11 10:17 UTC
I'm sending topic between multiple roscore environments by pulling & advertising.
When topic size is large, topic is overlooked and is not received.
Size of unreceived topic is following.

```
$ rostopic bw /selected_pointcloud
subscribed to [/selected_pointcloud]
average: 347.72KB/s
mean: 467.10KB min: 463.90KB max: 470.30KB window: 2
average: 253.39KB/s
mean: 467.10KB min: 463.90KB max: 470.30KB window: 2
```

@garaemon

**Comment by jihoonl** [comment] 2014-12-14 04:37
The size of topic should not be a problem of multimaster since it is just setting up a topic channel. It does not involved in actual data transferring.

Can you explain the situation in detail? How you setup and how you tested them?

**Comment by stonier** [comment] 2015-08-18 04:08
Unable to reproduce and closing for lack of data to resolve the problem.

**Closed as completed by stonier** 2015-08-18 04:08 UTC
Labels: bug, wontfix
